### ISSUE TITLE
erreur ajout sous famille

### ISSUE THREAD

**Issue by Mecadoctor** [KadarH/mecaworks#1]
Error
Message: L'ajout de la Sous-famille a echouée,famille introuvable 
![issue 1](https://user-images.githubusercontent.com/39465576/40282103-769f9f1e-5c59-11e8-9712-902924b4fbba.png)

**Comment by salah3x** [comment]
je n'arrive pas à reproduire l'erreur.
passe-moi les valeurs du formulaire précedent

**Comment by Mecadoctor** [comment]
N importe quelle sous famille fait erreur.  Exemple:
Nom : duster
Type compteur: km
Consom max km : 7
Capacité reservoir : 70
Famille :voiture legere
Marque: dacia duster

Essaye le f site et pas sur localhost ;)

**Comment by salah3x** [comment]
![screenshot from 2018-05-21 12-13-29](https://user-images.githubusercontent.com/23082235/40307095-bf9c8780-5cf0-11e8-8e32-7d11b7c0fc77.png)

**Comment by Mecadoctor** [comment]
Parfait.  Ca marche
