### ISSUE TITLE
#13 issue 13 probleme de la base

### ISSUE THREAD

**Issue by Mecadoctor** [KadarH/mecaworks#13]
quand on ajoute un nouveau chantier- nouveau engin- nouveau bon
![issue 13](https://user-images.githubusercontent.com/39465576/40691460-7d42d464-639b-11e8-80c3-26da179a031f.png)

**Comment by KadarH** [comment]
Aprés Debug , les chantiers qui n'ont aucun bon causaient le problème . ces chantiers ne paraitrons pas dans l'output .

Voir size of lists : 
![image](https://user-images.githubusercontent.com/23250431/40693769-c2601f68-63a8-11e8-9576-d56e5a17fab9.png)

les totals contient 11 , les locataires contiennent 7 . ce qui génère le probleme

**Comment by salah3x** [comment]
still the same problem
we can either exclude those who don't have 'bons' or give them a default of 0.
the first one seems more logical since we can't deal with chantier with no data and we shouldn't just assign 0 to each attribute.

**Comment by salah3x** [comment]
but the user should be able to see all the 'chantier' in dashboard.
@Mecadoctor  we need more clarifications.
