### ISSUE TITLE
calcul consommation prevue

### ISSUE THREAD

**Issue by Mecadoctor** [KadarH/mecaworks#15]
le calcul consommation prevue est incorrecte.

entre parenthèse:
(((((((((((((

Consommation prevue = heure travaillé de l'engin * consommation moyenne de l'engin
Avec consommation moyenne engin = est la moyenne des 20 dernieres consommation du meme engin. Le probleme c'est que  les 20 dernieres consommation contiennent des élements perturbant.
exemple 
un engin consomme 10L/H .un jour le gasoil a été volé de l'engin donc elle monte à 90L/h.
la moyenne des 20 dernieres consommation donc passe de 10L/h à une valeur trop grande influencé par 90L/H.

La solution est de limiter les consommations à la consommation max dans la table sous famille ( seuil d'alerte)

donc l'exemple ci dessous au lieu de faire la moyenne avec 90L/h on la remplace par exemple par 20L/h ( consommation max sous famille)

)))))))))) fin parenthèse

la consommation prévue est incorrecte à cause du calcul de la consommation moyenne dans la table engin (expliqué entre parenthèse). 
On remarque qu'elle est par défaut 30L/h
![issue consommation moyenne calcul](https://user-images.githubusercontent.com/39465576/40753001-9a7a711a-6461-11e8-8705-e0a3eae5fb03.png)

**Comment by KadarH** [comment]
L'attribut consommation moyenne ( dans la table Engin ) est fixé par défaut  30 .
le 1 er jour de chaque mois , on a un batch qui modifier la valeur de cet attribut pour tout les engin , et cela en calculant la moyenne de consommation de ces bons dans le mois precedent . 

Je m'explique : 

- au début de chaque mois , on prends la liste des bons du mois dernier ( pour un engin ) puis calcul la moyenne de consommation ( pour les bons dont la consommation est calculée ) . [ et cela pour tout les engins ]

Vous dites que : il ya des bons dont la consommation est très grande ( ce qui va perturber le calcul ) .
Vous proposez comme solution :  On prendra la liste des bons ( pour l'engin ) et pour toute les valeurs de consommation > consommation max de la sous famille liée. on la plafonne . 

Questions : 
-> Est ce que c çà le problème ? et c'est çà la solution ?
-> Pour les engins qui ne sont présents dans aucun bon , quelle valeur doit-on affecter à leur consommation moyenne ?
