### ISSUE TITLE
ajout nouveau bon engin avec un code égale au precedent

### ISSUE THREAD

**Issue by Mecadoctor** [KadarH/mecaworks#16]
ajout nouveau bon engin avec un code égale au precedent. ca donne erreur
![issue ajout bon avec meme code](https://user-images.githubusercontent.com/39465576/40753925-f4356b34-6465-11e8-9d7e-d44f2538e1e8.png)

**Comment by KadarH** [comment]
Le code de l'engin est un attribut unique dans la table . Ce qui veut dire, c'est une erreur normale .
