### ISSUE TITLE
issue calcul stock c

### ISSUE THREAD

**Issue by Mecadoctor** [KadarH/mecaworks#17]
![issue calcul stock c](https://user-images.githubusercontent.com/39465576/40754268-f2e23580-6467-11e8-8e0b-58bb14c02850.png)
![issue calcul stock c 2](https://user-images.githubusercontent.com/39465576/40754274-ffc551a6-6467-11e8-962d-dd71feb47995.png)

le calcul stock c est erroné. j'ai cree deux chantiers id=4 et id=5. j'ai saisi un bon engin pour chaque chantier , les résultat sont érronés

**Comment by KadarH** [comment]
Le problème ici , c'est que la recherche du dernier stock ne se faisait pas sur un chantier donnée , mais sur tout les chantiers 

 :-1: 
![image](https://user-images.githubusercontent.com/23250431/40788971-d94893de-64e0-11e8-8b0c-13f463b07cdd.png)
Ce qui doit être : 
:+1: 
![image](https://user-images.githubusercontent.com/23250431/40789006-ee37faa0-64e0-11e8-8dde-5f38042ee18d.png)

+ il faut régler le calcul du stock lors de la sais d'un bon de livraison En ajoutant la methode fillBonLivraison() avant de l'ajouter . De même pour bonFournisseur. :
