### ISSUE TITLE
erreur alerte compteur en panne

### ISSUE THREAD

**Issue by Mecadoctor** [KadarH/mecaworks#2]
erreur alerte compteur en panne , automatiquement une alerte se crée compteur réparé ( même cas km et Heure) 
![issue 2](https://user-images.githubusercontent.com/39465576/40282142-356dc0ce-5c5a-11e8-8653-b22716f535bb.png)

**Comment by salah3x** [comment]
@KadarH ach ban lik hna ?

**Comment by Mecadoctor** [comment]
Testé. C est ok avec heure et avec km
