### ISSUE TITLE
affichage table bon 

### ISSUE THREAD

**Issue by Mecadoctor** [KadarH/mecaworks#3]
afficher le code engin au lieu de N série engin
![issue 3](https://user-images.githubusercontent.com/39465576/40282304-ea3b8782-5c5c-11e8-9e9c-080ebf0ba04a.png)

**Comment by salah3x** [comment]
Code designe 'Code du bon'
la 4eme colonne 'Engin' = code de l'engin

**Comment by Mecadoctor** [comment]
C est ok.
  C est possible la colonne engin soit en deuxieme place apres la colonne date?

**Comment by Mecadoctor** [comment]
Parfait
