### ISSUE TITLE
Change stock after every bon

### ISSUE THREAD

**Issue by KadarH** [KadarH/mecaworks#30]
Update stock chantier after adding bon

**Comment by Mecadoctor** [comment]
Pour gerer le stock il faut verifier deux regles:
1- il n est pas possible de saisir un bon (engin/livraison/foufnisseur) qui a une date inférieur a la date du dernier inventaire. 
2 - pour chaque ajout d un nouveau bon. Il faut:
       A- classer tous les bons du chantier par date. (table stock) ; a partir du dernier inventaire. 
       B- classer tous les bons de la même date par id (table stock) ; a partir du dernier inventaire. 
       C - calculer le stock c avec S0 = stock dernier inventaire.
