### ISSUE TITLE
New Attribute needed

### ISSUE THREAD

**Issue by KadarH** [KadarH/mecaworks#4]
Add attribute **Nombre_Heure** to BonEngin 
Nombre_heure = number of hours the engin has worked

**Comment by salah3x** [comment]
does this need to be added to BonEngin form or it's calculated automatically from 'compteur' in addBonEngin()?
should I add it to BonEngin list ?

**Comment by KadarH** [comment]
No , this attribute will help us to calculate **Charge Total + Charge locataire** 
Don't add it to the BonEngin Form , but you can add it to the list of Bons
