### ISSUE TITLE
optionnel ( affiché résumé ) dans les filtres

### ISSUE THREAD

**Issue by Mecadoctor** [KadarH/mecaworks#48]
http://setrat.mecaworks.com/user/filter/be

![image](https://user-images.githubusercontent.com/39465576/46911237-778d9900-cf4d-11e8-9949-ed07b34b4a7e.png)

afficher la liste des engins sans redandance, et devans chaque engin : consommation moyenne, nombre d'heure travaillé, max compteur absolu,....

**Comment by salah3x** [comment]
non faisable car le menu des actions est pour chaque bon.
c'est mieux d'ajouter une autre page qui contient ces infos.

**Comment by salah3x** [comment]
BonEngin a **22 attributs**: 

*date, code, chantierGazoil, chantierTravail, engin, pompiste, chauffeur,
compteurPompe, quantite, compteurKm, compteurH, compteurHenPanne,
compteurKmenPanne, plein, carburant, compteurAbsoluKm, compteurAbsoluH,
consommationKm, consommationH, consommationH, consommationH et chargeHoraire.*

Pour grouper par engin il faut :

* eliminer des attributs comme chantier de travail car un engin peut avoir plusieur chantier de travail.
* remplacer des attributs par une valeur moyenne comme la consommation.
* remplacer des attributs par une valeur max (ex: date => date du dernier bon).
* ...

on doit prendre une decision pour chaque attribut.

**Comment by salah3x** [comment]
![1](https://user-images.githubusercontent.com/23082235/47604418-8ebe9300-d9f1-11e8-93b7-8cef7b2a2774.jpg)
![2](https://user-images.githubusercontent.com/23082235/47604419-9120ed00-d9f1-11e8-93d1-84702933704c.jpg)
![3](https://user-images.githubusercontent.com/23082235/47604420-94b47400-d9f1-11e8-95f8-e27f3d241153.jpg)
