### ISSUE TITLE
[Add a convenient title]

### ISSUE THREAD

**Issue by salah3x** [KadarH/mecaworks#52]
Quand tu entre un bon engin par exemple vehicule 50 < il a un compteur km› et par faute j entre tp05 qui a un compteur h.  Il va me donner erreur technique compteur illogique. Mais quand je corrige le bon engin vl50. Il fait entrer dans la base de donnee phpmyadmin compteur km et aussi le compteur h qui a été corrigé

**Comment by KadarH** [comment]
ceci doit être gérer au niveau de Js , une fois l'input est caché , sa valeur vaut 0 .
