### ISSUE TITLE
new page filtre par resume : consommation

### ISSUE THREAD

**Issue by Mecadoctor** [KadarH/mecaworks#53]
1- filtre by chantier gasoil : à supprimer ( seulement chantier travail)
2- calcul consommation : calculer la moyenne sans tenir des 0. c'est à dire ne pas calculer les consommation nulle ( comme la consommation moyenne dans : http://setrat.mecaworks.com/user/filter/be)

**Comment by salah3x** [comment]
par exemple:
- bon 1 : consommationH = 10, consommationKm = 0
- bon 2 : consommationH = 0, consommationKm = 20
- bon 3 : consommationH = 15, consommationKm = 30

alors consommationH moyenne = (10+15)/2 et consommationKm moyenne = (20+30)/2  ??

**Comment by Mecadoctor** [comment]
Oui mais

Le lun. 29 oct. 2018 13:04, Salah E. Loukili <notifications@github.com> a
écrit :

**Comment by Mecadoctor** [comment]
Oui

Le lun. 29 oct. 2018 13:04, Salah E. Loukili <notifications@github.com> a
écrit :
