### ISSUE TITLE
Gasoil dashboard not working after deleting an Engin

### ISSUE THREAD

**Issue by salah3x** [KadarH/mecaworks#56]
- **Error Message :**

Opération echouée, problème de la base 

- **Causes :**

Unable to find me.kadarh.mecaworks.domain.others.Engin with id 578; nested exception is javax.persistence.EntityNotFoundException: Unable to find me.kadarh.mecaworks.domain.others.Engin with id 578

- **Temporary solution:**

Disable delete button in Engin's list (admin section)

**Comment by KadarH** [comment]
- Get that
it works on local
I will disable delete Engin for this moment

**Comment by salah3x** [comment]
we still have to figure out the a permanent solution for this issue.

**Comment by salah3x** [comment]
When deleting an Engin, all of the associated BonEngin should be deleted by calling delete() on BonEnginService to delete the stocks too.

**Comment by KadarH** [comment]
i tried , but i faced the loop beans problem 
The dependencies of some of the beans in the application context form a cycle:

   enginController defined in file [/home/kad/IdeaProjects/mecaworks/target/classes/me/kadarh/mecaworks/controller/admin/EnginController.class]
┌─────┐
|  enginServiceImpl defined in file [/home/kad/IdeaProjects/mecaworks/target/classes/me/kadarh/mecaworks/service/impl/EnginServiceImpl.class]
↑     ↓
|  bonEnginServiceImpl defined in file [/home/kad/IdeaProjects/mecaworks/target/classes/me/kadarh/mecaworks/service/impl/bons/BonEnginServiceImpl.class]
↑     ↓
|  calculAbsoluServiceImpl defined in file [/home/kad/IdeaProjects/mecaworks/target/classes/me/kadarh/mecaworks/service/impl/bons/bonEngin/CalculAbsoluServiceImpl.class]
↑     ↓
|  fillServiceImpl defined in file [/home/kad/IdeaProjects/mecaworks/target/classes/me/kadarh/mecaworks/service/impl/bons/bonEngin/FillServiceImpl.class]
└─────┘

I will try another way.

**Comment by KadarH** [comment]
J'ai appelé  BonEnginRepo dans un  EnginServiceImpl pour palier au problème.
Resolu

**Comment by salah3x** [comment]
Apré suppression d'un bonEngin, son stock doit être supprimer aussi. (#44)
